[package]
name = "dioxus-lazy"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-web = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-signals = { git = "https://github.com/dioxuslabs/dioxus" }
dioxus-resize-observer = { git = "https://github.com/dioxus-community/dioxus-resize-observer" }
dioxus-use-mounted = { git = "https://github.com/matthunz/dioxus-use-mounted" }
log = "0.4.20"
dioxus-logger = "0.4.1"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.87"
web-sys = { version = "0.3.56", features = ["CanvasRenderingContext2d", "HtmlCanvasElement", "HtmlElement", "TextMetrics"] }
js-sys = "0.3.65"
futures = "0.3.29"
